version: 3
version_hash: HrLjWDRMvwV/w2FwIaHfWwk5HCGX57apTbyiXpkc9IU=
engine_version: 11
name: climatic_values_to_gcs
tables:
  _dlt_version:
    columns:
      version:
        data_type: bigint
        nullable: false
      engine_version:
        data_type: bigint
        nullable: false
      inserted_at:
        data_type: timestamp
        nullable: false
      schema_name:
        data_type: text
        nullable: false
      version_hash:
        data_type: text
        nullable: false
      schema:
        data_type: text
        nullable: false
    write_disposition: skip
    resource: _dlt_version
    description: Created by DLT. Tracks schema updates
  _dlt_loads:
    columns:
      load_id:
        data_type: text
        nullable: false
      schema_name:
        data_type: text
        nullable: true
      status:
        data_type: bigint
        nullable: false
      inserted_at:
        data_type: timestamp
        nullable: false
      schema_version_hash:
        data_type: text
        nullable: true
    write_disposition: skip
    resource: _dlt_loads
    description: Created by DLT. Tracks completed loads
  climatic_values:
    columns:
      fecha:
        data_type: text
        nullable: false
      indicativo:
        data_type: text
        nullable: false
      nombre:
        data_type: text
        nullable: false
      provincia:
        data_type: text
        nullable: false
      altitud:
        data_type: double
        nullable: false
      tmed:
        data_type: double
        nullable: true
      prec:
        data_type: text
        nullable: true
      tmin:
        data_type: double
        nullable: true
      horatmin:
        data_type: text
        nullable: true
      tmax:
        data_type: double
        nullable: true
      horatmax:
        data_type: text
        nullable: true
      hr_max:
        data_type: text
        nullable: true
      hora_hr_max:
        data_type: text
        nullable: true
      hr_min:
        data_type: double
        nullable: true
      hora_hr_min:
        data_type: text
        nullable: true
      ano:
        data_type: bigint
        nullable: false
      _dlt_load_id:
        data_type: text
        nullable: false
      _dlt_id:
        data_type: text
        nullable: false
        unique: true
        row_key: true
      hr_media:
        data_type: double
        nullable: true
      dir:
        data_type: text
        nullable: true
      velmedia:
        data_type: double
        nullable: true
      racha:
        data_type: double
        nullable: true
      horaracha:
        data_type: text
        nullable: true
      pres_max:
        data_type: double
        nullable: true
      hora_pres_max:
        data_type: text
        nullable: true
      pres_min:
        data_type: double
        nullable: true
      hora_pres_min:
        data_type: text
        nullable: true
      sol:
        data_type: double
        nullable: true
    write_disposition: replace
    resource: climatic_values
    x-normalizer:
      seen-data: true
  _dlt_pipeline_state:
    columns:
      version:
        data_type: bigint
        nullable: false
      engine_version:
        data_type: bigint
        nullable: false
      pipeline_name:
        data_type: text
        nullable: false
      state:
        data_type: text
        nullable: false
      created_at:
        data_type: timestamp
        nullable: false
      version_hash:
        data_type: text
        nullable: true
      _dlt_load_id:
        data_type: text
        nullable: false
      _dlt_id:
        data_type: text
        nullable: false
        unique: true
        row_key: true
    write_disposition: append
    file_format: preferred
    resource: _dlt_pipeline_state
    x-normalizer:
      seen-data: true
settings:
  detections:
  - iso_timestamp
  default_hints:
    not_null:
    - _dlt_id
    - _dlt_root_id
    - _dlt_parent_id
    - _dlt_list_idx
    - _dlt_load_id
    parent_key:
    - _dlt_parent_id
    root_key:
    - _dlt_root_id
    unique:
    - _dlt_id
    row_key:
    - _dlt_id
normalizers:
  names: snake_case
  json:
    module: dlt.common.normalizers.json.relational
previous_hashes:
- 5b5bFe59KOQLuSRtI5ZzTt7dlso+qAZQGcx4OF2DEME=
- SEPWoZbxkzVeFldZB5Ta5tt0WYKG0QoU8HSy3DhSxRU=
- BzvMDbIN2FvVdBg6WKobMm6ClBlmPtQr/O2x3CSu4TU=
